{
 "title": "Cockpit",
 "tags": [ "HCCM" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "car_vin",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"Car_Status\", tag: \"vin\", start:1999-01-01T00:00:00Z)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mileage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mileage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Fuel Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuelLevel\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"stateOfCharge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  }
 ]
}