{
 "title": "KFZ",
 "tags": [ "HCCM" ],
 "time": { "from": "2022-10-14T22:00:00.000Z", "to": "2023-10-14T22:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "car_vin",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"Car_Status\", tag: \"vin\", start:1999-01-01T00:00:00Z)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fahrten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tripsElectric\" or r[\"_field\"] == \"tripsTotal\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with tripsMixed: r.tripsTotal - r.tripsElectric}))"
    }
   ]
  },
  {
   "title": "Stromverbrauch - Anzeige und tatsächlicher Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyConsumedTotal\" or r[\"_field\"] == \"electricEnergyChargedTotal\")\r\n"
    }
   ]
  },
  {
   "title": "Stromkosten / 100 km",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedElectric\" or r[\"_field\"] == \"mileageElectricChargeCycles\"or r[\"_field\"] == \"electricityPrice\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with consumptionNormCost: r.electricityPrice * 100.0 * r.electricEnergyChargedElectric / float(v: r.mileageElectricChargeCycles)}))\r\n  |> drop(columns: [\"electricEnergyChargedElectric\", \"mileageElectricChargeCycles\", \"electricityPrice\"])"
    }
   ]
  },
  {
   "title": "Gefahrene Strecke",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mileageElectric\" or r[\"_field\"] == \"mileageTotal\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with mileageMixed: r.mileageTotal - r.mileageElectric}))\r\n"
    }
   ]
  },
  {
   "title": "Stromverbrauch - Rein elektrische und gemischte Fahrten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedElectric\" or r[\"_field\"] == \"electricEnergyChargedTotal\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with electricEnergyChargedMixed: r.electricEnergyChargedTotal - r.electricEnergyChargedElectric}))"
    }
   ]
  },
  {
   "title": "Benzinkosten / 100 km",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedElectric\" or r[\"_field\"] == \"electricEnergyChargedTotal\" or r[\"_field\"] == \"mileageElectricChargeCycles\" or r[\"_field\"] == \"mileageTotal\" or r[\"_field\"] == \"fuelConsumed\" or r[\"_field\"] == \"fuelPrice\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with mileageMixed: r.mileageTotal - r.mileageElectricChargeCycles}))\r\n  |> map(fn: (r) => ({r with electricEnergyChargedMixed: r.electricEnergyChargedTotal - r.electricEnergyChargedElectric}))\r\n  |> map(fn: (r) => ({r with consumptionNorm: 100.0 * r.electricEnergyChargedElectric / float(v: r.mileageElectricChargeCycles)}))\r\n  |> map(fn: (r) => ({r with mileageMixedEl: 100.0 * r.electricEnergyChargedMixed / r.consumptionNorm}))\r\n  |> map(fn: (r) => ({r with mileageMixedRed: float(v: r.mileageMixed) - r.mileageMixedEl}))\r\n  |> map(fn: (r) => ({r with fuelConsumptionNormCost: r.fuelPrice * 100.0 * r.fuelConsumed / r.mileageMixedRed}))\r\n  |> drop(columns: [\"electricEnergyChargedElectric\", \"electricEnergyChargedTotal\", \"mileageElectricChargeCycles\", \"mileageTotal\", \"fuelConsumed\", \"mileageMixed\", \"electricEnergyChargedMixed\", \"consumptionNorm\", \"mileageMixedEl\", \"mileageMixedRed\", \"fuelPrice\"])"
    }
   ]
  },
  {
   "title": "Fahrzeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"traveltimeElectric\" or r[\"_field\"] == \"traveltimeTotal\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with traveltimeMixed: r.traveltimeTotal - r.traveltimeElectric}))\r\n"
    }
   ]
  },
  {
   "title": "Stromverbrauch / 100 km",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "  from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedElectric\" or r[\"_field\"] == \"electricEnergyConsumedElectricChargeCycles\" or r[\"_field\"] == \"mileageElectricChargeCycles\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with consumptionNorm: 100.0 * r.electricEnergyChargedElectric / float(v: r.mileageElectricChargeCycles)}))\r\n  |> map(fn: (r) => ({r with consumptionDisp: 100.0 * r.electricEnergyConsumedElectricChargeCycles / float(v: r.mileageElectricChargeCycles)}))\r\n  |> drop(columns: [\"electricEnergyChargedElectric\", \"mileageElectricChargeCycles\", \"electricEnergyConsumedElectricChargeCycles\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Gesamtkosten - Benzin und Strom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedTotal\" or r[\"_field\"] == \"fuelConsumed\" or r[\"_field\"] == \"fuelPrice\" or r[\"_field\"] == \"electricityPrice\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with costElectricity: r.electricEnergyChargedTotal * r.electricityPrice}))\r\n  |> map(fn: (r) => ({r with costFuel: r.fuelConsumed * r.fuelPrice}))\r\n  |> map(fn: (r) => ({r with costTotal: r.costElectricity + r.costFuel}))\r\n  |> drop(columns: [\"electricEnergyChargedTotal\", \"fuelConsumed\", \"fuelPrice\", \"electricityPrice\"])"
    }
   ]
  },
  {
   "title": "Benzinverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuelConsumed\")\r\n"
    }
   ]
  },
  {
   "title": "Benzinverbrauch / 100 km (aus gemischten Fahrten ohne Elektro-Anteil)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedElectric\" or r[\"_field\"] == \"electricEnergyChargedTotal\" or r[\"_field\"] == \"mileageElectricChargeCycles\" or r[\"_field\"] == \"mileageTotal\"or r[\"_field\"] == \"fuelConsumed\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with mileageMixed: r.mileageTotal - r.mileageElectricChargeCycles}))\r\n  |> map(fn: (r) => ({r with electricEnergyChargedMixed: r.electricEnergyChargedTotal - r.electricEnergyChargedElectric}))\r\n  |> map(fn: (r) => ({r with consumptionNorm: 100.0 * r.electricEnergyChargedElectric / float(v: r.mileageElectricChargeCycles)}))\r\n  |> map(fn: (r) => ({r with mileageMixedEl: 100.0 * r.electricEnergyChargedMixed / r.consumptionNorm}))\r\n  |> map(fn: (r) => ({r with mileageMixedRed: float(v: r.mileageMixed) - r.mileageMixedEl}))\r\n  |> map(fn: (r) => ({r with fuelConsumptionNorm: 100.0 * r.fuelConsumed / r.mileageMixedRed}))\r\n  |> drop(columns: [\"electricEnergyChargedElectric\", \"electricEnergyChargedTotal\", \"mileageElectricChargeCycles\", \"mileageTotal\", \"fuelConsumed\", \"mileageMixed\", \"electricEnergyChargedMixed\", \"consumptionNorm\", \"mileageMixedEl\", \"mileageMixedRed\"])\r\n"
    }
   ]
  },
  {
   "title": "Einsparung Benzin",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Monthly\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricEnergyChargedElectric\" or r[\"_field\"] == \"electricEnergyChargedTotal\" or r[\"_field\"] == \"mileageElectricChargeCycles\" or r[\"_field\"] == \"mileageTotal\"or r[\"_field\"] == \"fuelConsumed\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with mileageMixed: r.mileageTotal - r.mileageElectricChargeCycles}))\r\n  |> map(fn: (r) => ({r with electricEnergyChargedMixed: r.electricEnergyChargedTotal - r.electricEnergyChargedElectric}))\r\n  |> map(fn: (r) => ({r with consumptionNorm: 100.0 * r.electricEnergyChargedElectric / float(v: r.mileageElectricChargeCycles)}))\r\n  |> map(fn: (r) => ({r with mileageMixedEl: 100.0 * r.electricEnergyChargedMixed / r.consumptionNorm}))\r\n  |> map(fn: (r) => ({r with mileageMixedRed: float(v: r.mileageMixed) - r.mileageMixedEl}))\r\n  |> map(fn: (r) => ({r with fuelConsumptionNorm: 100.0 * r.fuelConsumed / r.mileageMixedRed}))\r\n  |> map(fn: (r) => ({r with fuelSaved: r.fuelConsumptionNorm * float(v: r.mileageTotal) / 100.0 - r.fuelConsumed}))\r\n  |> drop(columns: [\"electricEnergyChargedElectric\", \"electricEnergyChargedTotal\", \"mileageElectricChargeCycles\", \"mileageTotal\", \"fuelConsumed\", \"mileageMixed\", \"electricEnergyChargedMixed\", \"consumptionNorm\", \"mileageMixedEl\", \"mileageMixedRed\", \"fuelConsumptionNorm\"])\r\n"
    }
   ]
  }
 ]
}