{
 "title": "Car Status",
 "tags": [ "HCCM" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_vin",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"Car_Status\", tag: \"vin\", start:1999-01-01T00:00:00Z)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fill Level Gas Tank",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuelLevel\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Charging Level HV Battery - Charging Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"stateOfCharge\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"Car_Charging\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\r\n  |> filter(fn: (r) => r[\"sublocation\"] == \"$car_vin\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Mileage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mileage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Energy HV Battery - Charged Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Status\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carStatus\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"batteryEnergy\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"Car_Charging\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"charged\")\r\n  |> filter(fn: (r) => r[\"sublocation\"] == \"$car_vin\")\r\n"
    }
   ]
  },
  {
   "title": "Trips",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "tStartDef = 2022-10-01\r\ntStart = if v.timeRangeStart < tStartDef then v.timeRangeStart else tStartDef\r\ntStop = if v.timeRangeStop < now() then now() else v.timeRangeStop\r\nfrom(bucket: \"Car_Trips\")\r\n  |> range(start: tStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trip_shortTerm\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> drop(columns: [\"_measurement\", \"_start\", \"_stop\", \"vin\", \"reportReason\", \"tripID\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  }
 ]
}