{
 "title": "Car Consumption",
 "tags": [ "HCCM" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "car_vin",
    "label": "VIN",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"Car_Status\", tag: \"vin\", start:1999-01-01T00:00:00Z)"
   }
  ]
 },
 "panels": [
  {
   "title": "Trips - Purely electric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Trips\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trip_shortTerm\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> drop(columns: [\"_measurement\", \"_start\", \"_stop\", \"vin\", \"reportReason\", \"tripID\", \"fuelConsumed\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> group(columns: [\"startMileage\"])\r\n  |> tail(n: 1)\r\n  |> filter(fn: (r) => r[\"fuelConsumed\"] == 0 and r[\"tripMileage\"] > 0)\r\n  |> map(fn: (r) => ({ r with endMileage: r.startMileage + r.tripMileage }))\r\n  |> drop(columns: [\"startMileage\", \"endMileage\", \"fuelConsumed\", \"traveltime\", \"electricPowerConsumed\"])\r\n  |> cumulativeSum(columns: [\"tripMileage\"])"
    },
    {
     "query": "from(bucket: \"Car_Trips\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trip_shortTerm\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> drop(columns: [\"_measurement\", \"_start\", \"_stop\", \"vin\", \"reportReason\", \"tripID\", \"fuelConsumed\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> group(columns: [\"startMileage\"])\r\n  |> tail(n: 1)\r\n  |> filter(fn: (r) => r[\"fuelConsumed\"] == 0 and r[\"tripMileage\"] > 0)\r\n  |> drop(columns: [\"startMileage\", \"endMileage\", \"fuelConsumed\", \"traveltime\", \"electricPowerConsumed\"])"
    },
    {
     "query": "from(bucket: \"Car_Trips\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trip_shortTerm\")\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> drop(columns: [\"_measurement\", \"_start\", \"_stop\", \"vin\", \"reportReason\", \"tripID\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"])\r\n  |> group(columns: [\"startMileage\"])\r\n  |> tail(n: 1)\r\n  |> filter(fn: (r) => r[\"fuelConsumed\"] > 0 and r[\"tripMileage\"] > 0)\r\n  |> drop(columns: [\"startMileage\", \"endMileage\", \"fuelConsumed\", \"traveltime\", \"electricPowerConsumed\"])"
    }
   ]
  },
  {
   "title": "Charged Energy - purely electric Trips",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"CarCharger\" or r[\"source\"] == \"tripMixed\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> map(fn: (r) => ({r with tag: if r.source == \"CarCharger\" then 1 else 0}))\r\n  |> duplicate(column: \"tag\", as: \"tag2\")\r\n  |> difference(columns: [\"tag2\"], nonNegative: false, keepFirst: true, initialZero: true)\r\n  |> filter(fn: (r) => r[\"source\"] == \"CarCharger\" and r[\"tag2\"] == 0)\r\n  |> drop(columns: [\"process\", \"source\", \"tag\", \"tag2\", \"vin\"]) \r\n  |> cumulativeSum()"
    },
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"CarCharger\" or r[\"source\"] == \"tripMixed\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> map(fn: (r) => ({r with tag: if r.source == \"CarCharger\" then 1 else 0}))\r\n  |> duplicate(column: \"tag\", as: \"tag2\")\r\n  |> difference(columns: [\"tag2\"], nonNegative: false, keepFirst: true, initialZero: true)\r\n  |> filter(fn: (r) => r[\"source\"] == \"CarCharger\" and r[\"tag2\"] == 0)\r\n  |> drop(columns: [\"process\", \"source\", \"tag\", \"tag2\", \"vin\"])  "
    }
   ]
  },
  {
   "title": "Charged Energy - All Trips - Comparison Charging vs. Car Display",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"process\"] == \"charge\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> drop(columns: [\"process\", \"source\", \"vin\"])"
    },
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"process\"] == \"decharge\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> drop(columns: [\"process\", \"source\", \"vin\"])"
    },
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"process\"] == \"decharge\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> drop(columns: [\"process\", \"source\", \"vin\"])\r\n  |> cumulativeSum()  "
    },
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"process\"] == \"charge\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> drop(columns: [\"process\", \"source\", \"vin\"]) \r\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Fuel Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel\")\r\n  |> filter(fn: (r) => r[\"process\"] == \"engine\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> drop(columns: [\"process\", \"source\", \"vin\"])"
    },
    {
     "query": "from(bucket: \"Car_Consumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"vin\"] == \"$car_vin\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel\")\r\n  |> filter(fn: (r) => r[\"process\"] == \"engine\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> sort(columns: [\"_time\", \"process\"])\r\n  |> drop(columns: [\"process\", \"source\", \"vin\"])\r\n  |> cumulativeSum()"
    }
   ]
  }
 ]
}